// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../src/content/docs/index.mdx?collection=docs"), "hooks/use-auto-resize-textarea.mdx": () => import("../src/content/docs/hooks/use-auto-resize-textarea.mdx?collection=docs"), "components/action-search-bar.mdx": () => import("../src/content/docs/components/action-search-bar.mdx?collection=docs"), "components/ai-input.mdx": () => import("../src/content/docs/components/ai-input.mdx?collection=docs"), "components/alert.mdx": () => import("../src/content/docs/components/alert.mdx?collection=docs"), "components/avatar-picker.mdx": () => import("../src/content/docs/components/avatar-picker.mdx?collection=docs"), "components/background-circles.mdx": () => import("../src/content/docs/components/background-circles.mdx?collection=docs"), "components/background-paths.mdx": () => import("../src/content/docs/components/background-paths.mdx?collection=docs"), "components/beams-background.mdx": () => import("../src/content/docs/components/beams-background.mdx?collection=docs"), "components/bento-grid.mdx": () => import("../src/content/docs/components/bento-grid.mdx?collection=docs"), "components/button.mdx": () => import("../src/content/docs/components/button.mdx?collection=docs"), "components/card.mdx": () => import("../src/content/docs/components/card.mdx?collection=docs"), "components/faq.mdx": () => import("../src/content/docs/components/faq.mdx?collection=docs"), "components/list.mdx": () => import("../src/content/docs/components/list.mdx?collection=docs"), "components/loader.mdx": () => import("../src/content/docs/components/loader.mdx?collection=docs"), "components/profile.mdx": () => import("../src/content/docs/components/profile.mdx?collection=docs"), "components/svg.mdx": () => import("../src/content/docs/components/svg.mdx?collection=docs"), "components/toolbar.mdx": () => import("../src/content/docs/components/toolbar.mdx?collection=docs"), "components/tweet-card.mdx": () => import("../src/content/docs/components/tweet-card.mdx?collection=docs"), "components/vercel-chat.mdx": () => import("../src/content/docs/components/vercel-chat.mdx?collection=docs"), }),
};
export default browserCollections;